// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WEB_MVC.Data;

#nullable disable

namespace WEBMVC.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230310192733_InitMigration")]
    partial class InitMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.2");

            modelBuilder.Entity("WEB_MVC.Models.Brand", b =>
                {
                    b.Property<int>("ConcernId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ConcernId");

                    b.ToTable("Brands");
                });

            modelBuilder.Entity("WEB_MVC.Models.Concerns", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BrandId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Concerns");
                });

            modelBuilder.Entity("WEB_MVC.Models.Phone", b =>
                {
                    b.Property<int>("BrandId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Price")
                        .HasColumnType("INTEGER");

                    b.Property<int>("_Category")
                        .HasColumnType("INTEGER");

                    b.Property<int>("_Color")
                        .HasColumnType("INTEGER");

                    b.Property<int>("_Data")
                        .HasColumnType("INTEGER");

                    b.HasKey("BrandId");

                    b.ToTable("Phones");
                });

            modelBuilder.Entity("WEB_MVC.Models.Brand", b =>
                {
                    b.HasOne("WEB_MVC.Models.Concerns", "_Concern")
                        .WithMany("Brands")
                        .HasForeignKey("ConcernId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("_Concern");
                });

            modelBuilder.Entity("WEB_MVC.Models.Phone", b =>
                {
                    b.HasOne("WEB_MVC.Models.Brand", "_Brand")
                        .WithMany("Phones")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("_Brand");
                });

            modelBuilder.Entity("WEB_MVC.Models.Brand", b =>
                {
                    b.Navigation("Phones");
                });

            modelBuilder.Entity("WEB_MVC.Models.Concerns", b =>
                {
                    b.Navigation("Brands");
                });
#pragma warning restore 612, 618
        }
    }
}
